apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-server
  labels:
    app: simple-node-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-node-server
  template:
    metadata:
      labels:
        app: simple-node-server
    spec:
      containers:
        - name: main
          image: simple-node-server:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: 250Mi
              cpu: 0.25m
          env:
            - name: PORT
              value: "80"
            - name: HOST
              value: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-node-server
spec:
  selector:
    app: simple-node-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-go-server
  labels:
    app: simple-go-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-go-server
  template:
    metadata:
      labels:
        app: simple-go-server
    spec:
      containers:
        - name: main
          image: simple-go-server:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: 250Mi
              cpu: 0.25m
          env:
            - name: PORT
              value: "80"
            - name: HOST
              value: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-go-server
spec:
  selector:
    app: simple-go-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
